In [16]:
import fastf1
import pandas as pd
from datetime import datetime

In [17]:
calendar = fastf1.get_event_schedule(2026)
calendar

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
0,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 1 2026,2026-02-13,Pre-Season Testing,testing,Practice 1,2026-02-11 10:00:00+03:00,2026-02-11 07:00:00,...,Practice 3,2026-02-13 10:00:00+03:00,2026-02-13 07:00:00,None,NaT,NaT,None,NaT,NaT,True
1,0,Bahrain,Bahrain,FORMULA 1 ARAMCO PRE-SEASON TESTING 2 2026,2026-02-20,Pre-Season Testing,testing,Practice 1,2026-02-18 10:00:00+03:00,2026-02-18 07:00:00,...,Practice 3,2026-02-20 10:00:00+03:00,2026-02-20 07:00:00,None,NaT,NaT,None,NaT,NaT,True
2,1,Australia,Melbourne,FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX ...,2026-03-08,Australian Grand Prix,conventional,Practice 1,2026-03-06 12:30:00+11:00,2026-03-06 01:30:00,...,Practice 3,2026-03-07 12:30:00+11:00,2026-03-07 01:30:00,Qualifying,2026-03-07 16:00:00+11:00,2026-03-07 05:00:00,Race,2026-03-08 15:00:00+11:00,2026-03-08 04:00:00,True
3,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2026,2026-03-15,Chinese Grand Prix,sprint_qualifying,Practice 1,2026-03-13 11:30:00+08:00,2026-03-13 03:30:00,...,Sprint,2026-03-14 11:00:00+08:00,2026-03-14 03:00:00,Qualifying,2026-03-14 15:00:00+08:00,2026-03-14 07:00:00,Race,2026-03-15 15:00:00+08:00,2026-03-15 07:00:00,True
4,3,Japan,Suzuka,FORMULA 1 ARAMCO JAPANESE GRAND PRIX 2026,2026-03-29,Japanese Grand Prix,conventional,Practice 1,2026-03-27 11:30:00+09:00,2026-03-27 02:30:00,...,Practice 3,2026-03-28 11:30:00+09:00,2026-03-28 02:30:00,Qualifying,2026-03-28 15:00:00+09:00,2026-03-28 06:00:00,Race,2026-03-29 14:00:00+09:00,2026-03-29 05:00:00,True
5,4,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2026,2026-04-12,Bahrain Grand Prix,conventional,Practice 1,2026-04-10 14:30:00+03:00,2026-04-10 11:30:00,...,Practice 3,2026-04-11 15:30:00+03:00,2026-04-11 12:30:00,Qualifying,2026-04-11 19:00:00+03:00,2026-04-11 16:00:00,Race,2026-04-12 18:00:00+03:00,2026-04-12 15:00:00,True
6,5,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2026,2026-04-19,Saudi Arabian Grand Prix,conventional,Practice 1,2026-04-17 16:30:00+03:00,2026-04-17 13:30:00,...,Practice 3,2026-04-18 16:30:00+03:00,2026-04-18 13:30:00,Qualifying,2026-04-18 20:00:00+03:00,2026-04-18 17:00:00,Race,2026-04-19 20:00:00+03:00,2026-04-19 17:00:00,True
7,6,United States,Miami Gardens,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2026,2026-05-03,Miami Grand Prix,sprint_qualifying,Practice 1,2026-05-01 12:30:00-04:00,2026-05-01 16:30:00,...,Sprint,2026-05-02 12:00:00-04:00,2026-05-02 16:00:00,Qualifying,2026-05-02 16:00:00-04:00,2026-05-02 20:00:00,Race,2026-05-03 16:00:00-04:00,2026-05-03 20:00:00,True
8,7,Canada,Montréal,FORMULA 1 LENOVO GRAND PRIX DU CANADA 2026,2026-05-24,Canadian Grand Prix,sprint_qualifying,Practice 1,2026-05-22 12:30:00-04:00,2026-05-22 16:30:00,...,Sprint,2026-05-23 12:00:00-04:00,2026-05-23 16:00:00,Qualifying,2026-05-23 16:00:00-04:00,2026-05-23 20:00:00,Race,2026-05-24 16:00:00-04:00,2026-05-24 20:00:00,True
9,8,Monaco,Monte Carlo,FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026,2026-06-07,Monaco Grand Prix,conventional,Practice 1,2026-06-05 13:30:00+02:00,2026-06-05 11:30:00,...,Practice 3,2026-06-06 12:30:00+02:00,2026-06-06 10:30:00,Qualifying,2026-06-06 16:00:00+02:00,2026-06-06 14:00:00,Race,2026-06-07 15:00:00+02:00,2026-06-07 13:00:00,True
10,9,Spain,Barcelona,FORMULA 1 MSC CRUISES GRAN PREMIO DE BARCELONA...,2026-06-14,Barcelona Grand Prix,conventional,Practice 1,2026-06-12 13:30:00+02:00,2026-06-12 11:30:00,...,Practice 3,2026-06-13 12:30:00+02:00,2026-06-13 10:30:00,Qualifying,2026-06-13 16:00:00+02:00,2026-06-13 14:00:00,Race,2026-06-14 15:00:00+02:00,2026-06-14 13:00:00,True
11,10,Austria,Spielberg,FORMULA 1 LENOVO AUSTRIAN GRAND PRIX 2026,2026-06-28,Austrian Grand Prix,conventional,Practice 1,2026-06-26 13:30:00+02:00,2026-06-26 11:30:00,...,Practice 3,2026-06-27 12:30:00+02:00,2026-06-27 10:30:00,Qualifying,2026-06-27 16:00:00+02:00,2026-06-27 14:00:00,Race,2026-06-28 15:00:00+02:00,2026-06-28 13:00:00,True
12,11,United Kingdom,Silverstone,FORMULA 1 PIRELLI BRITISH GRAND PRIX 2026,2026-07-05,British Grand Prix,sprint_qualifying,Practice 1,2026-07-03 12:30:00+01:00,2026-07-03 11:30:00,...,Sprint,2026-07-04 12:00:00+01:00,2026-07-04 11:00:00,Qualifying,2026-07-04 16:00:00+01:00,2026-07-04 15:00:00,Race,2026-07-05 15:00:00+01:00,2026-07-05 14:00:00,True
13,12,Belgium,Spa-Francorchamps,FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2026,2026-07-19,Belgian Grand Prix,conventional,Practice 1,2026-07-17 13:30:00+02:00,2026-07-17 11:30:00,...,Practice 3,2026-07-18 12:30:00+02:00,2026-07-18 10:30:00,Qualifying,2026-07-18 16:00:00+02:00,2026-07-18 14:00:00,Race,2026-07-19 15:00:00+02:00,2026-07-19 13:00:00,True
14,13,Hungary,Budapest,FORMULA 1 AWS HUNGARIAN GRAND PRIX 2026,2026-07-26,Hungarian Grand Prix,conventional,Practice 1,2026-07-24 13:30:00+02:00,2026-07-24 11:30:00,...,Practice 3,2026-07-25 12:30:00+02:00,2026-07-25 10:30:00,Qualifying,2026-07-25 16:00:00+02:00,2026-07-25 14:00:00,Race,2026-07-26 15:00:00+02:00,2026-07-26 13:00:00,True
15,14,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2026,2026-08-23,Dutch Grand Prix,sprint_qualifying,Practice 1,2026-08-21 12:30:00+02:00,2026-08-21 10:30:00,...,Sprint,2026-08-22 12:00:00+02:00,2026-08-22 10:00:00,Qualifying,2026-08-22 16:00:00+02:00,2026-08-22 14:00:00,Race,2026-08-23 15:00:00+02:00,2026-08-23 13:00:00,True
16,15,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026,2026-09-06,Italian Grand Prix,conventional,Practice 1,2026-09-04 12:30:00+02:00,2026-09-04 10:30:00,...,Practice 3,2026-09-05 12:30:00+02:00,2026-09-05 10:30:00,Qualifying,2026-09-05 16:00:00+02:00,2026-09-05 14:00:00,Race,2026-09-06 15:00:00+02:00,2026-09-06 13:00:00,True
17,16,Spain,Madrid,FORMULA 1 TAG HEUER GRAN PREMIO DE ESPAÑA 2026,2026-09-13,Spanish Grand Prix,conventional,Practice 1,2026-09-11 13:30:00+02:00,2026-09-11 11:30:00,...,Practice 3,2026-09-12 12:30:00+02:00,2026-09-12 10:30:00,Qualifying,2026-09-12 16:00:00+02:00,2026-09-12 14:00:00,Race,2026-09-13 15:00:00+02:00,2026-09-13 13:00:00,True
18,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2026-09-26,Azerbaijan Grand Prix,conventional,Practice 1,2026-09-24 12:30:00+04:00,2026-09-24 08:30:00,...,Practice 3,2026-09-25 12:30:00+04:00,2026-09-25 08:30:00,Qualifying,2026-09-25 16:00:00+04:00,2026-09-25 12:00:00,Race,2026-09-26 15:00:00+04:00,2026-09-26 11:00:00,True
19,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2026-10-11,Singapore Grand Prix,sprint_qualifying,Practice 1,2026-10-09 16:30:00+08:00,2026-10-09 08:30:00,...,Sprint,2026-10-10 17:00:00+08:00,2026-10-10 09:00:00,Qualifying,2026-10-10 21:00:00+08:00,2026-10-10 13:00:00,Race,2026-10-11 20:00:00+08:00,2026-10-11 12:00:00,True
20,19,United States,Austin,FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX...,2026-10-25,United States Grand Prix,conventional,Practice 1,2026-10-23 12:30:00-05:00,2026-10-23 17:30:00,...,Practice 3,2026-10-24 12:30:00-05:00,2026-10-24 17:30:00,Qualifying,2026-10-24 16:00:00-05:00,2026-10-24 21:00:00,Race,2026-10-25 15:00:00-05:00,2026-10-25 20:00:00,True
21,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2026,2026-11-01,Mexico City Grand Prix,conventional,Practice 1,2026-10-30 12:30:00-06:00,2026-10-30 18:30:00,...,Practice 3,2026-10-31 11:30:00-06:00,2026-10-31 17:30:00,Qualifying,2026-10-31 15:00:00-06:00,2026-10-31 21:00:00,Race,2026-11-01 14:00:00-06:00,2026-11-01 20:00:00,True
22,21,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2026-11-08,São Paulo Grand Prix,conventional,Practice 1,2026-11-06 12:30:00-03:00,2026-11-06 15:30:00,...,Practice 3,2026-11-07 11:30:00-03:00,2026-11-07 14:30:00,Qualifying,2026-11-07 15:00:00-03:00,2026-11-07 18:00:00,Race,2026-11-08 14:00:00-03:00,2026-11-08 17:00:00,True
23,22,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2026,2026-11-21,Las Vegas Grand Prix,conventional,Practice 1,2026-11-19 16:30:00-08:00,2026-11-20 00:30:00,...,Practice 3,2026-11-20 16:30:00-08:00,2026-11-21 00:30:00,Qualifying,2026-11-20 20:00:00-08:00,2026-11-21 04:00:00,Race,2026-11-21 20:00:00-08:00,2026-11-22 04:00:00,True
24,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2026,2026-11-29,Qatar Grand Prix,conventional,Practice 1,2026-11-27 16:30:00+03:00,2026-11-27 13:30:00,...,Practice 3,2026-11-28 17:30:00+03:00,2026-11-28 14:30:00,Qualifying,2026-11-28 21:00:00+03:00,2026-11-28 18:00:00,Race,2026-11-29 19:00:00+03:00,2026-11-29 16:00:00,True
25,24,United Arab Emirates,Yas Marina,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2026-12-06,Abu Dhabi Grand Prix,conventional,Practice 1,2026-12-04 13:30:00+04:00,2026-12-04 09:30:00,...,Practice 3,2026-12-05 14:30:00+04:00,2026-12-05 10:30:00,Qualifying,2026-12-05 18:00:00+04:00,2026-12-05 14:00:00,Race,2026-12-06 17:00:00+04:00,2026-12-06 13:00:00,True

In [18]:
now = datetime.now()

df_calendar = pd.DataFrame()

actual_year = now.year
actual_date_str = now.strftime("%Y-%m-%d")

print(f"Année : {actual_year}")
print(f"Date formatée : {actual_date_str}")

Année : 2026
Date formatée : 2026-03-12

In [24]:
def get_calendar(year):
    calendar = fastf1.get_event_schedule(year)
    
    df_calendar = calendar.copy()

    colonnes = [
        'RoundNumber','Country','Location','EventDate','EventName',
        'Session1','Session1DateUtc','Session2','Session2DateUtc',
        'Session3','Session3DateUtc','Session4','Session4DateUtc',
        'Session5','Session5DateUtc'
    ]
    
    df_calendar = df_calendar[colonnes]

    sessions_cols = ['Session1DateUtc', 'Session2DateUtc', 'Session3DateUtc','Session4DateUtc', 'Session5DateUtc']
    
    df_calendar['EventDate'] = pd.to_datetime(df_calendar['EventDate'])
    
    for col in sessions_cols:
        df_calendar[col] = pd.to_datetime(df_calendar[col]) + pd.Timedelta(hours=1)

    return df_calendar

In [20]:
df_calendar = get_calendar(actual_year,df_calendar)
df_calendar

,RoundNumber,Country,Location,EventDate,EventName,Session1,Session1DateUtc,Session2,Session2DateUtc,Session3,Session3DateUtc,Session4,Session4DateUtc,Session5,Session5DateUtc
0,0,Bahrain,Bahrain,2026-02-13,Pre-Season Testing,Practice 1,2026-02-11 08:00:00,Practice 2,2026-02-12 08:00:00,Practice 3,2026-02-13 08:00:00,None,NaT,None,NaT
1,0,Bahrain,Bahrain,2026-02-20,Pre-Season Testing,Practice 1,2026-02-18 08:00:00,Practice 2,2026-02-19 08:00:00,Practice 3,2026-02-20 08:00:00,None,NaT,None,NaT
2,1,Australia,Melbourne,2026-03-08,Australian Grand Prix,Practice 1,2026-03-06 02:30:00,Practice 2,2026-03-06 06:00:00,Practice 3,2026-03-07 02:30:00,Qualifying,2026-03-07 06:00:00,Race,2026-03-08 05:00:00
3,2,China,Shanghai,2026-03-15,Chinese Grand Prix,Practice 1,2026-03-13 04:30:00,Sprint Qualifying,2026-03-13 08:30:00,Sprint,2026-03-14 04:00:00,Qualifying,2026-03-14 08:00:00,Race,2026-03-15 08:00:00
4,3,Japan,Suzuka,2026-03-29,Japanese Grand Prix,Practice 1,2026-03-27 03:30:00,Practice 2,2026-03-27 07:00:00,Practice 3,2026-03-28 03:30:00,Qualifying,2026-03-28 07:00:00,Race,2026-03-29 06:00:00
5,4,Bahrain,Sakhir,2026-04-12,Bahrain Grand Prix,Practice 1,2026-04-10 12:30:00,Practice 2,2026-04-10 16:00:00,Practice 3,2026-04-11 13:30:00,Qualifying,2026-04-11 17:00:00,Race,2026-04-12 16:00:00
6,5,Saudi Arabia,Jeddah,2026-04-19,Saudi Arabian Grand Prix,Practice 1,2026-04-17 14:30:00,Practice 2,2026-04-17 18:00:00,Practice 3,2026-04-18 14:30:00,Qualifying,2026-04-18 18:00:00,Race,2026-04-19 18:00:00
7,6,United States,Miami Gardens,2026-05-03,Miami Grand Prix,Practice 1,2026-05-01 17:30:00,Sprint Qualifying,2026-05-01 21:30:00,Sprint,2026-05-02 17:00:00,Qualifying,2026-05-02 21:00:00,Race,2026-05-03 21:00:00
8,7,Canada,Montréal,2026-05-24,Canadian Grand Prix,Practice 1,2026-05-22 17:30:00,Sprint Qualifying,2026-05-22 21:30:00,Sprint,2026-05-23 17:00:00,Qualifying,2026-05-23 21:00:00,Race,2026-05-24 21:00:00
9,8,Monaco,Monte Carlo,2026-06-07,Monaco Grand Prix,Practice 1,2026-06-05 12:30:00,Practice 2,2026-06-05 16:00:00,Practice 3,2026-06-06 11:30:00,Qualifying,2026-06-06 15:00:00,Race,2026-06-07 14:00:00
10,9,Spain,Barcelona,2026-06-14,Barcelona Grand Prix,Practice 1,2026-06-12 12:30:00,Practice 2,2026-06-12 16:00:00,Practice 3,2026-06-13 11:30:00,Qualifying,2026-06-13 15:00:00,Race,2026-06-14 14:00:00
11,10,Austria,Spielberg,2026-06-28,Austrian Grand Prix,Practice 1,2026-06-26 12:30:00,Practice 2,2026-06-26 16:00:00,Practice 3,2026-06-27 11:30:00,Qualifying,2026-06-27 15:00:00,Race,2026-06-28 14:00:00
12,11,United Kingdom,Silverstone,2026-07-05,British Grand Prix,Practice 1,2026-07-03 12:30:00,Sprint Qualifying,2026-07-03 16:30:00,Sprint,2026-07-04 12:00:00,Qualifying,2026-07-04 16:00:00,Race,2026-07-05 15:00:00
13,12,Belgium,Spa-Francorchamps,2026-07-19,Belgian Grand Prix,Practice 1,2026-07-17 12:30:00,Practice 2,2026-07-17 16:00:00,Practice 3,2026-07-18 11:30:00,Qualifying,2026-07-18 15:00:00,Race,2026-07-19 14:00:00
14,13,Hungary,Budapest,2026-07-26,Hungarian Grand Prix,Practice 1,2026-07-24 12:30:00,Practice 2,2026-07-24 16:00:00,Practice 3,2026-07-25 11:30:00,Qualifying,2026-07-25 15:00:00,Race,2026-07-26 14:00:00
15,14,Netherlands,Zandvoort,2026-08-23,Dutch Grand Prix,Practice 1,2026-08-21 11:30:00,Sprint Qualifying,2026-08-21 15:30:00,Sprint,2026-08-22 11:00:00,Qualifying,2026-08-22 15:00:00,Race,2026-08-23 14:00:00
16,15,Italy,Monza,2026-09-06,Italian Grand Prix,Practice 1,2026-09-04 11:30:00,Practice 2,2026-09-04 15:00:00,Practice 3,2026-09-05 11:30:00,Qualifying,2026-09-05 15:00:00,Race,2026-09-06 14:00:00
17,16,Spain,Madrid,2026-09-13,Spanish Grand Prix,Practice 1,2026-09-11 12:30:00,Practice 2,2026-09-11 16:00:00,Practice 3,2026-09-12 11:30:00,Qualifying,2026-09-12 15:00:00,Race,2026-09-13 14:00:00
18,17,Azerbaijan,Baku,2026-09-26,Azerbaijan Grand Prix,Practice 1,2026-09-24 09:30:00,Practice 2,2026-09-24 13:00:00,Practice 3,2026-09-25 09:30:00,Qualifying,2026-09-25 13:00:00,Race,2026-09-26 12:00:00
19,18,Singapore,Marina Bay,2026-10-11,Singapore Grand Prix,Practice 1,2026-10-09 09:30:00,Sprint Qualifying,2026-10-09 13:30:00,Sprint,2026-10-10 10:00:00,Qualifying,2026-10-10 14:00:00,Race,2026-10-11 13:00:00
20,19,United States,Austin,2026-10-25,United States Grand Prix,Practice 1,2026-10-23 18:30:00,Practice 2,2026-10-23 22:00:00,Practice 3,2026-10-24 18:30:00,Qualifying,2026-10-24 22:00:00,Race,2026-10-25 21:00:00
21,20,Mexico,Mexico City,2026-11-01,Mexico City Grand Prix,Practice 1,2026-10-30 19:30:00,Practice 2,2026-10-30 23:00:00,Practice 3,2026-10-31 18:30:00,Qualifying,2026-10-31 22:00:00,Race,2026-11-01 21:00:00
22,21,Brazil,São Paulo,2026-11-08,São Paulo Grand Prix,Practice 1,2026-11-06 16:30:00,Practice 2,2026-11-06 20:00:00,Practice 3,2026-11-07 15:30:00,Qualifying,2026-11-07 19:00:00,Race,2026-11-08 18:00:00
23,22,United States,Las Vegas,2026-11-21,Las Vegas Grand Prix,Practice 1,2026-11-20 01:30:00,Practice 2,2026-11-20 05:00:00,Practice 3,2026-11-21 01:30:00,Qualifying,2026-11-21 05:00:00,Race,2026-11-22 05:00:00
24,23,Qatar,Lusail,2026-11-29,Qatar Grand Prix,Practice 1,2026-11-27 14:30:00,Practice 2,2026-11-27 18:00:00,Practice 3,2026-11-28 15:30:00,Qualifying,2026-11-28 19:00:00,Race,2026-11-29 17:00:00
25,24,United Arab Emirates,Yas Marina,2026-12-06,Abu Dhabi Grand Prix,Practice 1,2026-12-04 10:30:00,Practice 2,2026-12-04 14:00:00,Practice 3,2026-12-05 11:30:00,Qualifying,2026-12-05 15:00:00,Race,2026-12-06 14:00:00

In [ ]:
actual_date = pd.to_datetime(now.strftime("%Y-%m-%d"))
df_calendar['EventDate'] = pd.to_datetime(df_calendar['EventDate'])

index_proche = (df_calendar['EventDate'] - actual_date).abs().idxmin()

# On récupère la ligne complète
event_proche = df_calendar.loc[index_proche]

print(f"L'événement le plus proche est : {event_proche['EventName']} le {event_proche['EventDate']}")

L'événement le plus proche est : Chinese Grand Prix le 2026-03-15 00:00:00